# Digital library
services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    mem_limit: 2g
    environment:
      - TZ=Europe/Rome
    volumes:
      - /mnt/cache/container/appdata/kavita:/kavita/config
      - /mnt/hdd/simone/Backup/Read:/read:ro
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - container-share-net

networks:
  container-share-net:
    external: true