# Music streaming service
services:
  navidrome:
    image: deluan/navidrome:0.64.0
    container_name: navidrome
    user: 1000:100
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      - ND_CONFIGFILE=/data/navidrome.toml
      - ND_BACKUP_PATH=/backup
      - ND_BACKUP_SCHEDULE=0 0 * * *
      - ND_BACKUP_COUNT=7
      - ND_LISTENBRAINZ_ENABLED=true
      - ND_LISTENBRAINZ_BASEURL=http://${KOITO_IP}:4110/apis/listenbrainz/1
    volumes:
      - "/mnt/cache/container/appdata/navidrome/data:/data"
      - "/mnt/cache/container/data/music:/music:ro"
      - "/mnt/cache/container/appdata/navidrome/backup:/backup"
    networks:
      - container-share-net
    healthcheck:
          test: ["CMD", "wget", "-qO-", "http://localhost:4533/ping"]
          interval: 10m
          timeout: 10s
          retries: 3
          start_period: 1m
          start_interval: 5s

networks:
  container-share-net:
    external: true