# Offsite backup
services:
  kopia:
    image: "kopia/kopia:latest"
    container_name: "kopia"
    hostname: "${HOSTNAME}" # Prevent Kopia from losing history by recreating the container
    restart: unless-stopped
    ports:
      - "8087:8087"
    environment:
      - GODEBUG=madvdontneed=1
      - GOMEMLIMIT=700MiB
      - TZ=Europe/Rome
      - USER="${USER}"
      - KOPIA_PASSWORD=${KOPIA_PASSWORD}
      - KOPIA_SERVER_USERNAME=${KOPIA_SERVER_USERNAME}
      - KOPIA_SERVER_PASSWORD=${KOPIA_SERVER_PASSWORD}
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:8087
      - --enable-actions
    volumes:
      # Configuration
      - /mnt/cache/container/appdata/kopia/config:/app/config:rw
      - /mnt/cache/container/appdata/kopia/cache:/app/cache:rw
      - /mnt/cache/container/appdata/kopia/logs:/app/logs:rw
      - /mnt/cache/container/appdata/kopia/restore:/restore/:rw
      # Script e Socket
      - /mnt/cache/container/appdata/kopia/script:/script:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Backup
      - /mnt/hdd/simone:/backup/simone:ro
      - /mnt/hdd/alfredo:/backup/alfredo:ro
      - /mnt/cache/container:/backup/container:ro
    healthcheck:
      test: ["CMD-SHELL", "code=$$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8087/); [ \"$$code\" = \"200\" ] || [ \"$$code\" = \"401\" ]"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s